apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-login-deployment
  labels:
    app: argo-login
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-login
  template:
    metadata:
      labels:
        app: argo-login
    spec:
      containers:
      - name: argo-login
        image: akshaykmanoj/my-django-login:latest
        resourses:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: agro-login-service
spec:
  selector:
    app: agro-login
  ports:
  - name: name-of-service-port
    type: NodePort
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 32000
