apiVersion: v1
kind: Service
metadata:
  name: agro-login-service
spec:
  selector:
    app: agro-login
  ports:
  - name: name-of-service-port
    type: NodePort
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 32000
