---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agro-helm.fullname" . }}
  labels:
    app: {{ include "agro-helm.name" . }}
    chart: {{ include "agro-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      NodePort: {{ .Values.service.NodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "agro-helm.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agro-helm.fullname" . }}-preview
  labels:
    app: {{ include "agro-helm.name" . }}
    chart: {{ include "agro-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      NodePort: {{ .Values.service.NodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "agro-helm.name" . }}
    release: {{ .Release.Name }}




# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "agro-helm.fullname" . }}
#   labels:
#     {{- include "agro-helm.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: {{ .Values.service.targetPort }}
#       nodePort: {{ .Values.service.nodePort }}
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "agro-helm.selectorLabels" . | nindent 4 }}
